version: '3.2'

services:
  mysql-to-azure-backup:
    build:
      dockerfile: Dockerfile
      context: .
    image: mysql-to-azure-backup:latest
    network_mode: host
    environment:
      - mysql_host=localhost
      - mysql_port=3306
      - mysql_user=root
      - mysql_password=changeme
      - azure_account=
      - azure_accountKey=
      - azure_container=backup_container
