apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup-to-azure
  labels:
    app: mysql-backup
spec:
  schedule: '*/30 * * * *'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: mysql-backup-azure
              image: mysql-to-azure-backup
              imagePullPolicy: IfNotPresent
              env:
                - name: mysql_host
                  valueFrom:
                    secretKeyRef:
                      name: mysql-backup
                      key: host
                - name: mysql_port
                  valueFrom:
                    secretKeyRef:
                      name: mysql-backup
                      key: port
                - name: mysql_user
                  valueFrom:
                    secretKeyRef:
                      name: mysql-backup
                      key: user
                - name: mysql_password
                  valueFrom:
                    secretKeyRef:
                      name: mysql-backup
                      key: password
                - name: mysql_compress
                  valueFrom:
                    secretKeyRef:
                      name: mysql-backup
                      key: compress
                - name: mysql_encrypt
                  valueFrom:
                    secretKeyRef:
                      name: mysql-backup
                      key: encrypt
                - name: mysql_encryptKey
                  valueFrom:
                    secretKeyRef:
                      name: mysql-backup
                      key: encryptKey
                - name: azure_account
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: account
                - name: azure_accountKey
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: accountKey
                - name: azure_container
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: container
                - name: azure_backupfileprefix
                  valueFrom:
                    secretKeyRef:
                      name: azure
                      key: backupfilePrefix
          restartPolicy: Never
      backoffLimit: 1